version: "3.8"

services:
  db:
    image: postgres:latest
    restart: on-failure
    ports:
      - '8001:5432'
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - backend

  bot:
    build: ./bot
    image: alexcingolani/rti:rti_bot
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
    restart: on-failure

  api:
    build: ./api
    image: alexcingolani/rti:rti_api
    depends_on:
      - db
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`rtiapi.ddns.net`)
      - traefik.docker.network=traefik-public
    networks:
      - backend
      - traefik-public
       
    restart: on-failure

volumes:
  postgres-data:
  
networks:
  backend:
    driver: bridge
  traefik-public:
    external: true